name: Deployment for Project HDMI001

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AZURE_SUBSCRIPTION_ID: '{YOUR SUBSCRIPTION ID HERE}'           # Update to '{dataLandingZoneSubscriptionId}'
  AZURE_RESOURCE_GROUP_NAME: '{YOUR RESOURCE GROUP NAME HERE}'   # Update to '{dataLandingZoneName}-rg'
  AZURE_LOCATION: '{REGION ID HERE}'                             # Update to '{regionName}'
#  ACTIONS_RUNNER_DEBUG: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  prerequisite:
    runs-on: ubuntu-latest

    steps:
#      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - name: Check out from repo
#        uses: actions/checkout@v2 

#      - name: Debug stream
#        uses: mxschmitt/action-tmate@v3

      # Setting up Bicep
      - name: Setup Bicep
        uses: anthony-c-martin/setup-bicep@v0.1

      # Login to Azure
      - name: Azure Login
        id: azure_login
        uses: azure/login@v1.1
        env:
          CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS1 }} # finally works at GitHub Action
        with:
          creds: ${{ env.CREDENTIALS }}

      # Validate existence of resource group
      - name: Validating existence of resource group
        id: resource_group_storage
        uses: azure/cli@v1
        with:
          azcliversion: latest
          inlineScript: |
            echo "Validating existence of resource group ${{ env.AZURE_RESOURCE_GROUP_NAME }}"
            az group exists --name ${{ env.AZURE_RESOURCE_GROUP_NAME }}

      # Log out from Azure
      - name: Log out from Azure
        id: azure_logout
        uses: azure/cli@v1
        with:
          azcliversion: latest
          inlineScript: |
            az logout

  deployment-infra:
    needs: [ prerequisite ]
    runs-on: ubuntu-latest
    #if: github.event_name == 'push'

    steps:    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v2

      # Bicep All
      - name: Build All
        # path to your checked-in .bicep file to deploy
        #run: bicep build ${{ github.workspace }}/main-infra.bicep              
        # /opt/hostedtoolcache/bicep/x64/bicep
        run: |
          export PATH=/opt/hostedtoolcache/bicep/x64:$PATH
          "${GITHUB_WORKSPACE}/build.sh"

      # Login to Azure 
      - name: Azure Login
        id: azure_login
        uses: azure/login@v1.1
        env:
          CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS1 }}
        with:
          creds: ${{ env.CREDENTIALS }}

      # Deploy Infra
      - name: Deploy Infrastructure for Data Platform
        id: deploy_infra
        uses: azure/arm-deploy@v1
        continue-on-error: true
        with:
          scope: resourcegroup
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME }}
          region: ${{ env.AZURE_LOCATION }}
          template: ${{ github.workspace }}/main/main-infra.bicep
          parameters: ${{ github.workspace }}/main/main-infra.parameters.json
          deploymentMode: Incremental       

      # Deploy Key Vault
      - name: Deploy Key Vault for Data Platform
        id: deploy_key_vault
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME }}
          region: ${{ env.AZURE_LOCATION }}
          template: ${{ github.workspace }}/main/main-keyvault.bicep
          parameters: ${{ github.workspace }}/main/main-keyvault.parameters.json
          deploymentMode: Incremental                

      # Log out from Azure
      - name: Log out from Azure
        id: azure_logout
        uses: azure/cli@v1
        with:
          azcliversion: latest
          inlineScript: |
            az logout      

  deployment-services:
    needs: [ deployment-infra ]
    runs-on: ubuntu-latest
    #if: github.event_name == 'push'

    steps:    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v2

      # Bicep All
      - name: Build All
        # path to your checked-in .bicep file to deploy
        #run: bicep build ${{ github.workspace }}/main-infra.bicep              
        # /opt/hostedtoolcache/bicep/x64/bicep
        run: |
          export PATH=/opt/hostedtoolcache/bicep/x64:$PATH
          "${GITHUB_WORKSPACE}/build.sh"

      # Login to Azure 
      - name: Azure Login
        id: azure_login
        uses: azure/login@v1.1
        env:
          CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS1 }}
        with:
          creds: ${{ env.CREDENTIALS }}

      # Deploy Services All-at-once
      - name: Deploy Services All-at-once for Data Platform
        id: deploy_services
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME }}
          region: ${{ env.AZURE_LOCATION }}
          template: ${{ github.workspace }}/main/main-service-all-at-once.bicep
          parameters: ${{ github.workspace }}/main/main-service-all-at-once.parameters.json
          deploymentMode: Incremental                        

      # Log out from Azure
      - name: Log out from Azure
        id: azure_logout
        uses: azure/cli@v1
        with:
          azcliversion: latest
          inlineScript: |
            az logout      

